# Workflow name
name: 'Testing workflow basics'

on:
  workflow_dispatch:
    # Event inputs parameters
    inputs:
      environment:
        description: Test environment
        required: true
      branch-name:
        description: Branch name  # This is optional

env:
  SERVICE_NAME: dazn-performance-test

jobs:
  first-job:
    runs-on: ubuntu-latest
    name: first job in workflow
    outputs:
      something: ${{ steps.generate-output.outputs.my-name }}  # How to use outputs (for a job)
    steps:
      - name: "Chiru steps"
        id: generate-output  # This is to set uniqueness and an easy way to access a step in jobs
        run: |
          echo "Hello, GitHub Actions! ${{ github.event.inputs.environment }}"       # Using an event input parameter
          echo "Hello, GitHub Actions! ${{ github.event.inputs.branch-name }}"
          echo "Hello, GitHub Actions! ${{ env.SERVICE_NAME }}"       # Using an env variable
          echo "my-name=karthik"  >>  $GITHUB_OUTPUT
     - name: "Chiru steps 2"
        id: generate-output2  # This is to set uniqueness and an easy way to access a step in jobs
        run: |
          echo "Hello, GitHub Actions! ${{ steps.generate-output.outputs.my-name }}"       # Accessing output of previous step in current step
