# Testin first workflow
name: 'Testing worflow'

on : 
    workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, GitHub Actions!" 
      - run: echo "My secret key is $TEST_KEY"