name: Create File and Run Terraform

on:
  workflow_dispatch:
  
jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create File
      run: |
        echo "This is the content of my_file.txt" > ./my_file.txt
        ls -la ./my_file.txt # Debugging: List files in the workspace
        cat ./my_file.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-file
        path: ./my_file.txt

  use-file:
    needs: create-file
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: my-file
        path: my_file.txt

    - name: Use File
      run: |
        ls -la ./  # Debugging: List files in the workspace
        cat my_file.txt
